framework:
    # esi:              ~
    secret:             e0GmDlW4NmMQSGkHLhYrAu3AafcNmygR
    charset:            UTF-8
    router:             { resource: "%kernel.root_dir%/config/routing.yml" }
    form:               true
    csrf_protection:    true
    validation:         { enabled: true, enable_annotations: true }
    templating:         { engines: ['php'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true
        name:           hibaroo


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar



# Propel configuration
propel:
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    dbal:
        driver:               mysql
        options:              {}
        user:                 xxxxxxxx
        password:             xxxxxxxx
        dsn:                  mysql:host=localhost;dbname=xxxxxxx

## Swiftmailer Configuration
#swiftmailer:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx

